//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingSignalR.MWC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slots
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Status { get; set; }
        public int FloorId { get; set; }
        public int SlotTypeId { get; set; }
    
        public virtual Floor Floor { get; set; }
        public virtual SlotTypes SlotTypes { get; set; }
    }
}
